# -*- coding: utf-8 -*-
"""Trabalho SP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15af8TJvCCg4vXLMsSBVcPJMUDxoVDlqp
"""

import pandas as pd
import matplotlib as plt
df = pd.read_csv('TCC (3).csv')
lst = ['Nada','Idade','Autodeclaração','Gênero','Dias trabalhados','Horas trabalhadas','Aplicativos','Vínculo','Escolaridade','Exerce outra atividade','Tempo no ramo','Motivo','Veículo usado','Renda média','Gasto médio','RG1','BairroEntrega','RegiaoCasa','DSCENTRO','DSZL','DSZS','DSZO','DSZN','nada']
i = 0
for c in df.columns:
    df.rename(columns = { str(c) :  lst[i] }, inplace = True)
    i += 1
df.info()

j = 0
for i in df['Renda média']:
    if i == 'Abaixo de R$ 1045,00':
        df['Renda média'] = df['Renda média'].replace(i,'Entre R$ 601,00 e 1045,00')
    j+= 1
        
df['Renda média'].value_counts()

df['BairroEntrega'] = df['BairroEntrega'].str.upper()
df['BairroEntrega'].value_counts()

"""Obtendo o número de entrevistados que trabalham de 5 a 7 dias por semana mais de 8 horas por dia e depois obtendo a 
renda média desses trabalhadores.

Sabemos pela contagem que 66% dos entrevistados estão nessa condição (37 pessoas), 
e que desses 66%, 75% deles ganham menos que um salário mínimo ( 28 pessoas). 


"""

ab = df.loc[(df['Dias trabalhados'] == '5 a 6 dias') | (df['Dias trabalhados'] == 'Todos os dias') & (df['Horas trabalhadas'] == 'entre 8 e 12 horas')]
ab['Renda média'].value_counts()
for i in ab['Renda média']

cd = df.loc[(df['Tempo no ramo'] == '6 meses ou menos') & (df['Motivo'] == 'Por causa das dificuldades durante a pandemia')]
cd['Dias trabalhados'].value_counts()

ab = pd.crosstab(df['Tempo no ramo'],df['Motivo'])
ab

ab = pd.crosstab(df['Horas trabalhadas'],df['Renda média'])




#ab.plot.bar(ylabel = 'Frequência',figsize = (10,11))

j = 0
for i in df['Idade']:
    if i == '3':
        df['Idade'] = df['Idade'].replace(i,'15 - 18 anos')
    j+= 1
        
df['Idade'].value_counts()

ab = pd.crosstab(df['Idade'], df['Tempo no ramo'])
ab.plot.bar(ylabel = 'Número de pessoas')

!conda install geopandas



ab = df.loc[(df['Idade'] == '15 - 18 anos')] 
bg = ab.groupby('Tempo no ramo')
hj = bg['Autodeclaração'].value_counts()



ab = pd.crosstab(df['Idade'], df['Autodeclaração'])
ab.plot.bar(ylabel = 'Número de pessoas')

ab = pd.crosstab(df['Idade'], df['Tempo no ramo'])
ab.plot.bar(ylabel = 'Número de pessoas',figsize = (8,7))

import geopandas as gpd

sp = gpd.read_file('C:/Users/Pedro/Desktop/DEINFO_DISTRITO.shx')
sp.plot(figsize = (10,10),color = 'white',edgecolor = 'black')

df['DSCENTRO'].value_counts()

df['DSZN'].value_counts()

df['DSZS'].value_counts()

df['DSZL'].value_counts()

df['DSZO'].value_counts()

brrs = ['República','Pirituba','Brasilândia','Vila Medeiros','Freguesia do Ó','Cachoeirinha','Jaçanã','Grajaú','Campo Limpo','Jardim São Luís','Capão Redondo','Jardim Ângela','Parelheiros','Moema','Itaquera','Guaianases','Cidade Tiradentes','Vila Formosa','Sapopemba','Penha','Carrão','Jaguaré','Rio Pequeno','Butantã','Vila Sônia','Pinheiros']
nms = [1,4,2,1,1,1,1,3,3,2,2,2,1,1,3,2,1,1,1,1,1,2,2,2,1,1]
sp['Numero'] = 0
j = 0
l = 0
for k in brrs:
    for i in sp['Bairro']:
        if k == i:
            sp.loc[[j],['Numero']] = nms[l]
        j += 1
    l += 1
    j = 0

sp.plot(column = 'Numero', legend = True, figsize = (10,10),cmap = 'Oranges',edgecolor = 'black')

lista = ['José Bonifácio',
                'Jardim São Luís',
                'Artur Alvim',
                'Jaguará',
                'Vila Prudente',
                'Jaguaré',
                'Jaraguá',
                'Jardim Helena',
                'Jardim Paulista',
                'Lajeado',
                'Lapa',
                'Liberdade',
                'Limão',
                'Vila Medeiros',
                'Jardim Ângela',
                'Parelheiros',
                'Vila Sônia',
                'Água Rasa',
                'Alto de Pinheiros',
                'Anhanguera',
                'Aricanduva',
                'Barra Funda',
                'Bela Vista',
                'Belém', 
                'Bom Retiro', 
                'Brás', 
                'Brasilândia',
                'Butantã',
                'Cachoeirinha', 
                'Cambuci', 
                'Campo Belo', 
                'Campo Grande', 
                'Campo Limpo',
                'Cangaíba',
                'Capão Redondo', 
                'Carrão',
                'Casa Verde', 
                'Cidade Ademar',
                'Cidade Dutra',
                'Cidade Líder',
                'Cidade Tiradentes',
                'Consolação',
                'Cursino', 
                'Ermelino Matarazzo', 
                'Freguesia do Ó',
                'Grajaú', 
                'Guaianases', 
                'Iguatemi',
                'Ipiranga',
                'Itaim Bibi',
                'Itaim Paulista', #50
                'Itaquera', 
                'Jabaquara',
                'Jaçanã',
                'Mandaqui',
                'Marsilac',
                'Moema',
                'Mooca',
                'Morumbi',
                'Pari',
                'Parque do carmo',
                'Penha',
                'Pedreira',
                'Perdizes',
                'Perus',
                'Pinheiros',
                'Pirituba',
                'Ponte Rasa',
                'Raposo Tavares',
                'República',
                'Rio Pequeno', #70
                'Sacomã',
                'Santa Cecília',
                'Santana',
                'Santo Amaro',
                'São Domingos',
                'São Lucas',
                'São Mateus',
                'São Miguel',
                'São Rafael',
                'Sapopemba', # 80
                'Saúde',
                'Sé',
                'Socorro',
                'Tatuapé',  
                'Tremembé',
                'Tucuruvi',
                'Vila Andrade',
                'Vila Curuçá',
                'Vila Formosa',
                'Vila Guilherme', #90
                'Vila Jacuí',
                'Vila Leopoldina',
                'Vila Madalena',
                'Vila Maria',
                'Vila Mariana',
                'Vila Matilde']

_lis = []

    # removendo duplicados
for x in lista:
    if x not in _lis:
        _lis.append(x)
            
print(len(_lis))



brrs = ['Pinheiros','Itaim Bibi','Sé','Moema','Butantã','Jardim Paulista','Vila Mariana','Alto de Pinheiros','Lapa','Capão Redondo','Pirituba','Liberdade','Santa Cecília','Higienópolis','Tucuruvi','Mooca','Tatuapé']
nms = [8,9,5,4,2,4,3,4,2,2,1,2,1,1,1,1,1]
sp['Numero'] = 0
j = 0
l = 0
for k in brrs:
    for i in sp['Bairro']:
        if k == i:
            sp.loc[[j],['Numero']] = nms[l]
        j += 1
    l += 1
    j = 0

